[project]
name = "godoctopus"
version = "0.1.0"
description = "Amalgamate many branches into one GitHub Pages site"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.28.1",
]
