name: "Publish to GitHub Pages"
on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build and Export Game"
    types:
      - completed

# Cancel any ongoing previous run if the job is re-triggered
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

env:
  GODOT_VERSION: 4.3

jobs:
  check:
    name: Check if GitHub Pages is enabled
    runs-on: ubuntu-latest
    steps:
      - name: Check
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh api "repos/${{ github.repository }}/pages" | jq --exit-status '.build_type == "workflow"'
          then
              echo "enabled=true" >> "$GITHUB_OUTPUT"
          else
              echo "# Not published to GitHub Pages" >> "$GITHUB_STEP_SUMMARY"
              echo "" >> "$GITHUB_STEP_SUMMARY"
              echo -n "Check that Pages is enabled, with the source set to GitHub Actions, in the " >> "$GITHUB_STEP_SUMMARY"
              echo "[repository settings](https://github.com/${{ github.repository }}/settings/pages)." >> "$GITHUB_STEP_SUMMARY"
          fi
    outputs:
      enabled: ${{ steps.check.outputs.enabled }}

  publish:
    name: Assemble Pages Artifact
    needs:
      - check
    if: ${{ needs.check.outputs.enabled }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Assemble artifact
        id: assemble
        run: uv run --script godoctopus.py
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.assemble.outputs.path }}
